# Generated by Django 5.2.6 on 2025-09-13 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_designtask_developmenttask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='User',
            new_name='user',
        ),
    ]
